# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Catopedia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Catopedia
  pod 'Kingfisher'
  
  target 'CatopediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatopediaUITests' do
    # Pods for testing
  end

end
